import Head from "next/head";
import { Inter } from "@next/font/google";

/* For Testing Radix with Tailwind */
import * as Checkbox from "@radix-ui/react-checkbox";
import { CheckIcon } from "@radix-ui/react-icons";

export default function Components() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="m-10">
        <h1 className="text-3xl font-bold underline mb-4">Hello World</h1>
        <form className="mb-4">
          <div className="flex items-center">
            <Checkbox.Root
              className="bg-neutral-3 w-6 h-6 rounded flex items-center justify-center hover:bg-primary-3"
              defaultChecked
              id="c1"
            >
              <Checkbox.Indicator className="text-primary-11">
                <CheckIcon />
              </Checkbox.Indicator>
            </Checkbox.Root>
            <label
              className="pl-4 text-sm leading-none select-none"
              htmlFor="c1"
            >
              This is a check box to check if Radix works.
            </label>
          </div>
        </form>
        <p className="font-code">
          Hello this is a code segment to test the font and ligatures
        </p>
        <p className="font-code mb-4">{" === ==<  ==> -> == >="}</p>

        <h2 className="mb-2 font-bold text-xl">Site Colors</h2>

        <p className="text-md mb-2">Primary: </p>
        <div className="flex gap-2 mb-2">
          <div className="w-10 h-10 bg-primary-1" />
          <div className="w-10 h-10 bg-primary-2" />
          <div className="w-10 h-10 bg-primary-3" />
          <div className="w-10 h-10 bg-primary-4" />
          <div className="w-10 h-10 bg-primary-5" />
          <div className="w-10 h-10 bg-primary-6" />
          <div className="w-10 h-10 bg-primary-7" />
          <div className="w-10 h-10 bg-primary-8" />
          <div className="w-10 h-10 bg-primary-9" />
          <div className="w-10 h-10 bg-primary-10" />
          <div className="w-10 h-10 bg-primary-11" />
          <div className="w-10 h-10 bg-primary-12" />
        </div>
        <p className="text-md mb-2">Neutral: </p>
        <div className="flex gap-2 mb-4">
          <div className="w-10 h-10 bg-neutral-1" />
          <div className="w-10 h-10 bg-neutral-2" />
          <div className="w-10 h-10 bg-neutral-3" />
          <div className="w-10 h-10 bg-neutral-4" />
          <div className="w-10 h-10 bg-neutral-5" />
          <div className="w-10 h-10 bg-neutral-6" />
          <div className="w-10 h-10 bg-neutral-7" />
          <div className="w-10 h-10 bg-neutral-8" />
          <div className="w-10 h-10 bg-neutral-9" />
          <div className="w-10 h-10 bg-neutral-10" />
          <div className="w-10 h-10 bg-neutral-11" />
          <div className="w-10 h-10 bg-neutral-12" />
        </div>

        <h2 className="mb-2 font-bold text-xl">Sematic Colors</h2>
        <p className="text-md mb-2">Error: </p>
        <div className="flex gap-2 mb-4">
          <div className="w-10 h-10 bg-error-1" />
          <div className="w-10 h-10 bg-error-2" />
          <div className="w-10 h-10 bg-error-3" />
          <div className="w-10 h-10 bg-error-4" />
          <div className="w-10 h-10 bg-error-5" />
          <div className="w-10 h-10 bg-error-6" />
          <div className="w-10 h-10 bg-error-7" />
          <div className="w-10 h-10 bg-error-8" />
          <div className="w-10 h-10 bg-error-9" />
          <div className="w-10 h-10 bg-error-10" />
          <div className="w-10 h-10 bg-error-11" />
          <div className="w-10 h-10 bg-error-12" />
        </div>
        <p className="text-md mb-2">Success: </p>
        <div className="flex gap-2 mb-4">
          <div className="w-10 h-10 bg-success-1" />
          <div className="w-10 h-10 bg-success-2" />
          <div className="w-10 h-10 bg-success-3" />
          <div className="w-10 h-10 bg-success-4" />
          <div className="w-10 h-10 bg-success-5" />
          <div className="w-10 h-10 bg-success-6" />
          <div className="w-10 h-10 bg-success-7" />
          <div className="w-10 h-10 bg-success-8" />
          <div className="w-10 h-10 bg-success-9" />
          <div className="w-10 h-10 bg-success-10" />
          <div className="w-10 h-10 bg-success-11" />
          <div className="w-10 h-10 bg-success-12" />
        </div>
        <p className="text-md mb-2">Warning: </p>
        <div className="flex gap-2 mb-4">
          <div className="w-10 h-10 bg-warning-1" />
          <div className="w-10 h-10 bg-warning-2" />
          <div className="w-10 h-10 bg-warning-3" />
          <div className="w-10 h-10 bg-warning-4" />
          <div className="w-10 h-10 bg-warning-5" />
          <div className="w-10 h-10 bg-warning-6" />
          <div className="w-10 h-10 bg-warning-7" />
          <div className="w-10 h-10 bg-warning-8" />
          <div className="w-10 h-10 bg-warning-9" />
          <div className="w-10 h-10 bg-warning-10" />
          <div className="w-10 h-10 bg-warning-11" />
          <div className="w-10 h-10 bg-warning-12" />
        </div>
      </main>
    </>
  );
}
